name: RunMe Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Project_Path: RunMe.csproj 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 配置MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 恢复NuGet依赖（针对.csproj）
      - name: Restore dependencies
        run: msbuild $env:Project_Path /t:Restore /p:Configuration=${{ matrix.configuration }}

      # 构建项目（使用.csproj而非.sln）
      - name: Build project
        run: msbuild $env:Project_Path /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.2

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RunMe-${{ matrix.configuration }}
          path: |
            **/bin/${{ matrix.configuration }}/*.exe
