name: Build .NET Framework 4.7.2 App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore RunMe.csproj  # 直接还原项目依赖（如果有NuGet包）

      - name: Build project
        run: |
          msbuild RunMe.csproj `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform="AnyCPU" `
            /p:TargetFrameworkVersion=v4.7.2 `
            /p:OutputPath=bin\${{ matrix.configuration }} `
            /p:BaseOutputPath=bin\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RunMe-Build
          path: |
            bin/Release/*.exe