name: RunMe Build

# 触发条件：推送到master分支或对master的PR
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  # 构建两种配置

    runs-on: windows-latest  # 必须用Windows环境

    env:
      Solution_Name: RunMe.sln  # 解决方案名称（根据实际文件确认）

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 配置MSBuild（.NET Framework构建必需）
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 恢复NuGet依赖（如果项目有引用）
      - name: Restore dependencies
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

      # 构建项目
      - name: Build project
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.2

      # 上传构建产物（包含可执行文件和配置文件）
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RunMe-${{ matrix.configuration }}
          path: |
            **/bin/${{ matrix.configuration }}/*.exe
